# Form implementation generated from reading ui file './Python/gui/lickwin.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_lickWin(object):
    def setupUi(self, lickWin):
        lickWin.setObjectName("lickWin")
        lickWin.resize(376, 280)
        self.gridLayout = QtWidgets.QGridLayout(lickWin)
        self.gridLayout.setObjectName("gridLayout")
        self.plotWid = PlotWidget(lickWin)
        self.plotWid.setObjectName("plotWid")
        self.gridLayout.addWidget(self.plotWid, 0, 0, 1, 2)

        self.retranslateUi(lickWin)
        QtCore.QMetaObject.connectSlotsByName(lickWin)

    def retranslateUi(self, lickWin):
        _translate = QtCore.QCoreApplication.translate
        lickWin.setWindowTitle(_translate("lickWin", "Form"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    lickWin = QtWidgets.QWidget()
    ui = Ui_lickWin()
    ui.setupUi(lickWin)
    lickWin.show()
    sys.exit(app.exec())
