# Form implementation generated from reading ui file './Python/gui/mousewin.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mouseWin(object):
    def setupUi(self, mouseWin):
        mouseWin.setObjectName("mouseWin")
        mouseWin.resize(548, 419)
        self.gridLayout = QtWidgets.QGridLayout(mouseWin)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(mouseWin)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.liq_am_disp = QtWidgets.QLabel(mouseWin)
        self.liq_am_disp.setObjectName("liq_am_disp")
        self.gridLayout.addWidget(self.liq_am_disp, 0, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(mouseWin)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 0, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(mouseWin)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 3, 1, 1)
        self.line = QtWidgets.QFrame(mouseWin)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 4)
        self.label_2 = QtWidgets.QLabel(mouseWin)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.lick_thresh_disp = QtWidgets.QLabel(mouseWin)
        self.lick_thresh_disp.setObjectName("lick_thresh_disp")
        self.gridLayout.addWidget(self.lick_thresh_disp, 2, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(mouseWin)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 2, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(mouseWin)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 2, 3, 1, 1)
        self.line_2 = QtWidgets.QFrame(mouseWin)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 3, 0, 1, 4)
        self.plotWid = MplWidget(mouseWin)
        self.plotWid.setMinimumSize(QtCore.QSize(491, 281))
        self.plotWid.setObjectName("plotWid")
        self.gridLayout.addWidget(self.plotWid, 4, 0, 1, 4)

        self.retranslateUi(mouseWin)
        QtCore.QMetaObject.connectSlotsByName(mouseWin)

    def retranslateUi(self, mouseWin):
        _translate = QtCore.QCoreApplication.translate
        mouseWin.setWindowTitle(_translate("mouseWin", "Form"))
        self.label.setText(_translate("mouseWin", "Current Liquid Amount:"))
        self.liq_am_disp.setText(_translate("mouseWin", "2"))
        self.pushButton.setText(_translate("mouseWin", "Change"))
        self.label_2.setText(_translate("mouseWin", "Current Lick Threshold:"))
        self.lick_thresh_disp.setText(_translate("mouseWin", "1"))
        self.pushButton_2.setText(_translate("mouseWin", "Change"))
from gui.mplwidget import MplWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mouseWin = QtWidgets.QWidget()
    ui = Ui_mouseWin()
    ui.setupUi(mouseWin)
    mouseWin.show()
    sys.exit(app.exec())
