# Form implementation generated from reading ui file './Python/gui/mousewin.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mouseWin(object):
    def setupUi(self, mouseWin):
        mouseWin.setObjectName("mouseWin")
        mouseWin.resize(429, 192)
        self.pushButton = QtWidgets.QPushButton(mouseWin)
        self.pushButton.setGeometry(QtCore.QRect(50, 90, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(mouseWin)
        QtCore.QMetaObject.connectSlotsByName(mouseWin)

    def retranslateUi(self, mouseWin):
        _translate = QtCore.QCoreApplication.translate
        mouseWin.setWindowTitle(_translate("mouseWin", "Form"))
        self.pushButton.setText(_translate("mouseWin", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mouseWin = QtWidgets.QWidget()
    ui = Ui_mouseWin()
    ui.setupUi(mouseWin)
    mouseWin.show()
    sys.exit(app.exec())
