# Form implementation generated from reading ui file './Python/gui/odourwin.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_odourWin(object):
    def setupUi(self, odourWin):
        odourWin.setObjectName("odourWin")
        odourWin.resize(975, 391)
        self.gridLayout_3 = QtWidgets.QGridLayout(odourWin)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(odourWin)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.fileDisp = QtWidgets.QLabel(odourWin)
        self.fileDisp.setText("")
        self.fileDisp.setObjectName("fileDisp")
        self.gridLayout_3.addWidget(self.fileDisp, 0, 1, 1, 1)
        self.selectFileButton = QtWidgets.QPushButton(odourWin)
        self.selectFileButton.setObjectName("selectFileButton")
        self.gridLayout_3.addWidget(self.selectFileButton, 0, 2, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.patternEdit = QtWidgets.QTextEdit(odourWin)
        self.patternEdit.setObjectName("patternEdit")
        self.gridLayout_2.addWidget(self.patternEdit, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 0, 1, 3)

        self.retranslateUi(odourWin)
        QtCore.QMetaObject.connectSlotsByName(odourWin)

    def retranslateUi(self, odourWin):
        _translate = QtCore.QCoreApplication.translate
        odourWin.setWindowTitle(_translate("odourWin", "Form"))
        self.label.setText(_translate("odourWin", "File selected:"))
        self.selectFileButton.setText(_translate("odourWin", "Select File"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    odourWin = QtWidgets.QWidget()
    ui = Ui_odourWin()
    ui.setupUi(odourWin)
    odourWin.show()
    sys.exit(app.exec())
