# Form implementation generated from reading ui file './Python/gui/odourwin.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_odourWin(object):
    def setupUi(self, odourWin):
        odourWin.setObjectName("odourWin")
        odourWin.setGeometry(QtCore.QRect(0, 0, 400, 300))

        self.retranslateUi(odourWin)
        QtCore.QMetaObject.connectSlotsByName(odourWin)

    def retranslateUi(self, odourWin):
        _translate = QtCore.QCoreApplication.translate
        odourWin.setWindowTitle(_translate("odourWin", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    odourWin = QtWidgets.QWidget()
    ui = Ui_odourWin()
    ui.setupUi(odourWin)
    odourWin.show()
    sys.exit(app.exec())
